src/watch.coffee
This follows the footsteps of the node CLI and other Unix utilities
=> Exit watcher when stdin is closed

src/watch.coffee
Otherwise brunch build will wait for stdin to be closed
too and it won't exit properly.
=> Only listen to stdin if in persistent mode

src/fs_utils/file_list.coffee
Hi!
I recently face cases where the `dependent.dependencies` can be undefined (basically, I try to add jQuery to my project through npm).
I don't really know if it's normal or not but in any case, it safer to just check if `dependencies` is not undefined.
=> There are some cases where `dependent.dependencies` can be undefined

src/watch.coffee
Hey!
Recently I had an issue with brunch builds failing with versions >= 1.8 (https://github.com/brunch/brunch/issues/967)
The issue was due to the addition of the `path` argument in `watch()`
https://github.com/brunch/brunch/commit/9b9e8c5015856eb8e770f050232e092ee88e822e#diff-5894f29c43782173bc5f20c4d13a4f8d
In my case, it was failing because I had a deployment script that would build on the fly and deploy based on the env (override). This script would call `brunch.build options`, but with the addition of the `path` argument,  path was now being set to my `options` argument. I can get around this by simply adding `brunch.build null, options`. This isn't a difficult fix on my end, but I suspect others might run into the same issue.
This could be cleaned up a bit outside of the watch …
=> Handle optional `path` arg

src/helpers.coffee
```
/usr/local/lib/node_modules/brunch/lib/helpers.js:532
items = Object.keys(json.dependencies).filter(function(dep) {
^
TypeError: Object.keys called on non-object
at Function.keys (native)
at loadNpm (/usr/local/lib/node_modules/brunch/lib/helpers.js:532:18)
at addPackageManagers (/usr/local/lib/node_modules/brunch/lib/helpers.js:552:10)
at Object.exports.loadConfig (/usr/local/lib/node_modules/brunch/lib/helpers.js:595:10)
at initialize (/usr/local/lib/node_modules/brunch/lib/watch.js:460:18)
at new BrunchWatcher (/usr/local/lib/node_modules/brunch/lib/watch.js:649:5)
at module.exports.watch (/usr/local/lib/node_modules/brunch/lib/watch.js:708:10)
at start (/usr/local/lib/node_modules/brunch/lib/index.js:15:31)
at Command.listener …
```
=> Account for absent package dependencies.

docs/README.md, docs/commands.md, docs/config.md, docs/faq.md
* `docs/config.md`:
* Updated the default value for `conventions.vendor`: it’s `/(^bower_components|node_modules|vendor)[\\/]/`, but was said to be `/vendor[\\/]/`, which makes it hard to understand how Bower components are handled;
* Updated the default value for `conventions.ignored `: added `vendor/ruby-*/`, `vendor/jruby-*/`, and `vendor/bundle/`;
* Added mention of the `isVendor`argument for the `modules.wrapper` function;
* `docs/commands.md`: Corrected an example still using the old `brunch new` syntax with `--skeleton`;
* `docs/faq.md`: Added a mention of the `--debug` option;
* `docs/README.md`: I believe it’s _Any scripts in `app/` dirs_ that are wrapped by default into modules, and not only _Any scripts in `assets/` dirs_, which looks like a copy/paste mistake.
=> Documentation Fixes

src/helpers.coffee
Similar to the unofficial `overrides` keyword in `bower.json`, this patch adds support for an unofficial `overrides` keyword in `package.json`, in order to fix issue #986.
A supported `package.json` would be:
{
...
"dependencies": {
"react": "*"
},
"overrides": {
"react": {
"main": "dist/react.js"
}
}
}
=> Add "overrides" support for NPM.

docs/config.md, src/fs_utils/generate.coffee, src/helpers.coffee
This allow us to customize which files to automatically
require at the end of each joined file.
Closes #999. Alternative to #1000.
=> Support config.modules.autoRequire

src/helpers.coffee
In #987 the overrides support was added. After updating I noticed, that my build failed because `overrides` wasn't defined in my `package.json`. I think this shouldn't be required.
As I'm not using CoffeeScript regularly, I hope this is the correct way to do it.
=> Check whether json.overrides is defined

src/cli.coffee, src/watch.coffee
Closes #998
I would really appreciate if there was a release so we can update Phoenix to use the `--stdin` flag from now on.
Also, I did not make the flag hidden, because folks would see it and wonder what it is about. I tried to make it as descriptive as possible though.
Thank you!
=> Only listen to stdin if --stdin flag is given

docs/config.md, lib/application.js, lib/deppack.js, lib/fs_utils/generate.js, lib/fs_utils/pipeline.js, package.json
This improves upon deppack. #1023 
Some highlights:
* every used file from each package gets wrapped into a module (like "react/lib/Object.assign") — previously deppack exposed only index.js as "package-name"
* respecting `browser` property from package.json to require different files in the browser environment
* `process` shim to make some things work
* require tree is only traversed during watcher setup, making succ build significantly faster
* it is possibly to use direct dependencies' stylesheets files
* adding `material-ui` (or any other large package) doesn't break the build (#1038)
Example usage:
```coffee
exports.config =
npm:
enabled: true
packages: ['react', 'react-dom', 'react-router']
```
you can also use stylesheets & expose globals
```coffee
exports.config =
npm:
enabled: …
```
=> NPM integration for front-end packages

lib/deppack.js, lib/ui.js
Currently if one Ctrl+C's during the "compiling..." animation, the cursor in the shell will still be disabled. This aims to fix that.
=> Reset cursor when process is exited

lib/deppack.js
This is going to be useful to, for example, allow registering `exoskeleton` as `backbone` and make chaplin ok with it
=> Allow to create aliases for deppack modules

lib/application.js, lib/watch.js
Some editors, such as Emacs, make backups while saving. This causes
files to be momentarily empty before the new contents are written. This
then results in a race between Brunch and the editor, trying to compile
the file and write the file at the same time. See also issue #971.
As a workaround, it's possible to delay the watch. This adds a new
watcher config option `fixEditorSave`. When true, the watcher will wait
up to 50ms for the write to stabilize.
=> Small fix to watching for some editors

lib/deppack.js
See report here: https://github.com/phoenixframework/phoenix/issues/1463#issuecomment-170171217
Once the user reports it works on Windows, a 2.1.3 release
would be appreciated. I will drop a note here. :)
=> Properly split path on Windows

lib/deppack.js
I am trying to play with React + Omniscient using brunch.io 2.1.3. My minimal package.json looks like
```
{
"repository": {},
"dependencies": {
"babel-brunch": "^6.0.0",
"brunch": "^2.1.1",
"clean-css-brunch": ">= 1.0 < 1.8",
"css-brunch": ">= 1.0 < 1.8",
"immstruct": "^2.0.0",
"immutable": "^3.7.6",
"javascript-brunch": ">= 1.0 < 1.8",
"moment": "^2.11.0",
"omniscient": "^4.1.1",
"react": "^0.14.5",
"react-dom": "^0.14.5",
"sass-brunch": "^1.9.2",
"transducers-js": "^0.4.174",
"uglify-js-brunch": ">= 1.0 < 1.8"
},
"devDependencies": {
"babel-preset-react": "^6.3.13"
}
}
```
My brunch setup uses NPM to load modules. Here is the relevant section:
```
npm: {
enabled: true,
whitelist: [
'immutable',
'omniscient',
'immstruct',
'react',
'react-dom',
'transducers-js'
]
}
```
Omniscient is …
=> Use module's root path as relative path.

lib/deppack.js
This pull request fixes similar problem reported on #1035 and fixed on 37b3901 .
Currently `deppack.js` wrongly generates module name contain backslashes when `bundle build` is executed on Windows because of their backslash path separator. It should be normalized to front slashes to work properly, because when the module required, its name assumed to be separated with front slashes.
I found this issue when I tried to follow the post on my Windows development environment.
https://medium.com/@diamondgfx/phoenix-v1-1-2-and-react-js-3dbd195a880a
=> Normalize deppack's module name against Windows backslash path

lib/deppack.js
Fix a compilation issue with:
```
"browser": {
"./lib/locales": false,
"./lib/locales.js": false
},
```
https://github.com/brunch/brunch/issues/1108
=> Fix browser mapping with false values

docs/faq.md
Hi there.
Recently I've encountered a problem when I was need to override `main` attribute of some dependent  `package.json`.
Actually, I was need to grab only one .js file, but package `main` pointed to big compiled file.
After debugging for a while I've found, that brunch already supports overriding dependent packages manifests attributes not only for bower but for npm also.
I decided to update FAQ to help brunch's newcomers, maybe some of them facing it too.
=> Update faq with npm integration information

package.json
The underlying `resolve` library has a bug in versions <1.1.7 which means it doesn't work on Windows when using relative paths (like `.`). This breaks the `npm.globals` config on Windows. I can confirm that updating this dependency does fix it.
=> Update browser-resolve dependency.

lib/deppack.js
Hello there.
After updating to 2.2 *(2.1.3 fine)* I've found that overrides section from my package.json not working anymore.
Overriding package.json is implemented in `./lib/deppack.js`.
I found that `browserResolve` doesn't care about overrides in my local `./package.json` because it is trying to read original package.json of module (`./node_modules/cool-package/package.json`).
=> Override npm packages attributes fixes

lib/deppack.js, lib/fs_utils/file_list.js, lib/fs_utils/pipeline.js, package.json
This PR is missing a shim for `zlib`, because some of its deps relies on `require`ing json files and brunch/deppack don't currently handle that. Since `zlib` is probably the least used shim, it might be ok to leave it out for now.
Not sure, but could it make sense create a separate package just to depend on shim packages? Otherwise brunch's packages.json is going to be cluttered with that, and the purpose is not exactly obvious. I grouped these in a separate "section" in packages for now...
The PR still needs some cleaning up and rebasing, so don't merge just yet :)
=> Deppack shims

bin/brunch
`ver` is changed to `version`, fixes #1132
=> Change ver to version, fix #1132

lib/deppack.js
This fixes #1141. Just need to make sure the shim path is made relative.
=> Make process shim path relative

lib/fs_utils/source_file.js
Which is needed to properly handle source maps for pre-processed stylesheets
=> Properly support source maps with 2+ sources

lib/deppack/explore.js
Before [this commit](https://github.com/brunch/brunch/commit/0c1dec1dddff18664de40a52302d2d4814be6be9#diff-6f4bba58e4958ed5756cabd5f320a564), Brunch supported passing null as the second argument to a plugin's compile callback to generate no source code. The above commit broke this behaviour and throws an exception. This broke the jaded-brunch plugin. This change restores the old behaviour.
=> Fixed crash when compiling assets that don't generate JS source

lib/plugins.js
Since the `preCompilers` array is passed to `Promise.all` in the watcher, the array has to be of promises. 
Currently it contains functions so no pre-compiler gets fired. This PR addresses that by:
* making `preCompilers` an array of promises
* allowing individual `preCompile` to accept one argument, a callback
* **or,** allowing individual `preCompile` to accept no arguments and return a promise
* **or,** allowing individual `preCompile` to accept no arguments and return nothing
#1082
=> Make preCompile work

lib/deppack/modules.js, lib/deppack/process.js
This is going to allow to use v1 of some library in the app code, while
retaining the ability for some other dependency to rely on v2.
It works by generating module names like this for nested modules:
"some_dep/node_modules/conflicting_dep". In require, it tries to prepend
that prefix. If the require fails, it drops it and tries to require just
"dep".
The drawbacks of this iteration are the try-catch approach that first tries to load current_module/node_modules/required_module and falls back to required_module otherwise, but that could as well be improved at a later time.
=> Handle nested dependencies

lib/deppack/process.js
Should fix the issue mentioned in https://github.com/brunch/brunch/issues/1161#issuecomment-183551321
cc @razor-x
The dev mode off in prod build is a nice-to-have and will be added later
=> Don't create aliases for shims with proper names

lib/deppack/explore.js, lib/deppack/modules.js
Brunch build fails trying to resolve not installed optional deps from npm-installed dependency:
19 Feb 12:14:24 - error: Resolving deps of node_modules/exoskeleton/exoskeleton.js failed. Could not load module 'underscore' from '[...]/node_modules/exoskeleton'. Possible solution: run `npm install`.
This happens when using exoskeleton without underscore. The line in `exoskeleton.js` that triggers the error is this:
try { _ = require('underscore'); } catch(e) { }
The solution in this PR is to check scanned deps found in npm packages against the configured deps in the corresponding `package.json` file.
To restore the old behaviour one could add overrides to the main app's `package.json`. For the above example it would look like this:
...
"overrides": {
"exoskeleton": {
"dependencies": { …
=> Do not try to resolve optional deps scanned from npm packages.

package.json
Newer detective versions have only two dependencies instead of 13, and
should be slightly faster.
=> Update detective to 4.3.x

lib/deppack/explore.js
The PR failed to account for the fact that node modules can require:
a) relative paths (as in ./lib/React)
b) parts of themselves using their module name (as in a/b from module a)
c) shims
@paulmillr we probably should merge changes like this more carefully, probably by first testing if one of our react/exim apps builds and works fine.
=> Fix regression introduced in GH-1184

lib/deppack/explore.js, lib/deppack/modules.js
Another #1184-related regression discovered: https://github.com/brunch/brunch/issues/1136#issuecomment-189225521
This PR introduces a check that will use the dependency also if it is present in the `browser` field of the package.json
=> Fix a regression introduced with GH-1184

lib/deppack/explore.js
Reported in: #1209 
This is yet another regression related to GH-1184, which purpose was to
not raise errors when optional dependencies could not be found.
=> Don't assume `peerDependencies` are optional

lib/deppack/helpers.js
Per the docs, `conventions.vendor` can be set as an `anymatch` matcher but a small regression (comes from 0c1dec1dddff18664de40a52302d2d4814be6be9 it seems) made it Regex only.
This fix that by using anymatch again.
cc'ing @goshakkk just in case as he's the author of the aforementioned commit
=> Allow to specify again conventions.vendor as an anymatch set

lib/modules.js
Currently, when specifying `modules.wrapper` as a function, the `conventions.vendor` and `modules.nameCleaner` aren't respected.
This PR allow to :
- Not having to check if a file is a vendor one
- Not having to cleanup the module name manually
=> Align function as a wrapper with other types

lib/deppack/resolve.js, lib/watch.js, package.json
Makes issue of duplicate files reported in #1198 impossible on case-insensitive filesystems by making sure the resolved and actual FS path case-match.
=> Ensure deppack require discovery is case-sensitive

lib/modules.js
This is dependent on
https://github.com/brunch/commonjs-require-definition/pull/12.
This PR will allow the use of extensions in requiring module names such
as `require('./my-widget.html')`. It is just the minimum change to
allow this in the app code.
With the commonjs module change, `deppack/modules.js` might be made
simpler and more robust. The `package.json` “main” definition could use
aliases. Modules can be safely referenced with or without their
extensions. But I don’t feel comfortable making the changes required in
there yet.
=> Add support for module extensions

lib/deppack/modules.js
Returning nothing instead of memo breaks it
=> Fix the deppack overrides reducer

lib/watch.js, package.json
It will also automatically try to update dependencies to match
package.json.
Adds another 100ms or so (depending on package.json, obviously) to the startup time.
=> Check project dependencies when starting brunch

lib/fs_utils/source_file.js
Since `isNpmJSON` is set dynamically after `loadInit` is called, our code should always call `deppack.xyz`, instead of importing just `xyz`.
=> Use a qualified deppack.isNpmJSON call. Closes GH-1236

lib/config.js
The old and documented behavior is that overrides of files[type].key
should completely overwrite the said part of the main config, not be
merged with it.
=> Fix a regression introduces by 48cb5e0. Closes GH-1239

lib/config.js, lib/watch.js
This is to let deppack distinguish between modules and vendor files that
just happen to come from node_modules.
Reported in: https://github.com/brunch/with-react/issues/3
Partly related to: https://github.com/brunch/brunch/issues/1247 & https://github.com/brunch/deppack/pull/1
=> Add plugins' includes as npm.statics

docs/config.md, docs/plugins.md, lib/fs_utils/generate.js, lib/fs_utils/pipeline.js, lib/fs_utils/source_file.js, lib/fs_utils/write.js
Allows non-JS compilers to additionally expose a JS version of a file (use case: CSS modules, the compiler needs to both pre-process the source file + obfuscate class name, as well as create a JS module with class name mappings)
To achieve that, plugins that used to return `{data, map}` can now return `{data, map, exports}` where `exports` is a string containing javascript code:
```javascript
class MyCompiler {
compile(params) {
const path = params.path;
const data = params.data;
const compiled = magic(data);
const exports = "module.exports = 42";
return Promise.resolve({ data: compiled, exports });
}
}
```
Internally it is achieved by allowing a single file have multiple *targets* — at max, one per file type (javascript, stylesheet, template), which is enough to get the example above …
=> Compilers JS exports

lib/fs_utils/file_list.js
(ref brunch/stylus-brunch#34)
This is a regression caused by the move to using `Map`s for
`fileList.files`. The `compileDependencyParents` function iterated over
`fileList`, shadowing the children's `path` with that of the file being
iterated.
=> Fix parent recompilation when a dependency changes

lib/fs_utils/file_list.js
Hi there, thanks for this great project!
This PR fix an issue introduced in df88f11f4985fa3f94676e825b3e348fcebb6bfd.
While `this.files` has a `forEach` method, it's a `Map` instance so `this.assets.concat(this.files).forEach(file => file.dispose());` gives
```sh
TypeError: file.dispose is not a function
at /home/marcio/n/lib/node_modules/brunch/lib/fs_utils/file_list.js:228:57
at Array.forEach (native)
at FileList.dispose (/home/marcio/n/lib/node_modules/brunch/lib/fs_utils/file_list.js:228:36)
at Server.restart (/home/marcio/n/lib/node_modules/brunch/lib/watch.js:204:21)
at Server.g (events.js:261:16)
at emitNone (events.js:68:13)
at Server.emit (events.js:167:7)
at emitCloseNT (net.js:1525:8)
at nextTickCallbackWith1Arg (node.js:444:9)
at process._tickCallback (node.js:366:17)
```
This …
=> Fix TypeError: file.dispose is not a function

lib/fs_utils/write.js
Due to it, the parameters for the `sourceFiles` of `onCompile` callback
didn't retain properly the old behavior - template files would be
discarded from it. This commit is to address that issue.
The issue has caused some plugins, notably `static-jade-brunch` to stop functioning.
=> Fix a regression introduced by JS exports

lib/config.js
=> Don't categorize node_modules as 'assets' even if they match the regexp

lib/config.js
The entryPoints format is `entryPoint: outputFile`, and this PR is meant to provide a helpful error message if an user accidentally uses them in the wrong order (i.e. `outputFile: entryPoint`)
=> Print a warning if 'entryPoints' key-values are flipped

docs/faq.md, lib/fs_utils/generate.js, lib/fs_utils/source_file.js, lib/hmr.js, lib/watch.js
To do: 
After merged (in order):
What is intentionally missing from this PR:
- source maps for cases when `if (module.hot) { ... }` checks are cut — since production isn't going to need source maps anyway
- callback for self-accept `accept()` for when there is an error
Relevant PRs:
---
http://github.com/brunch/hmr-brunch
=> Hot Module Replacement API

lib/plugins.js
Hello there!
I've found a bug with duplicating plugins in package.json. Imagine situation:
```javascript
"dependencies": {
"my-cool-optimizer": "^0.0.1"
},
"devDependencies": {
"my-cool-optimizer": "^2.0.0"
}
```
In this case, optimizer from my-cool-optimizer plugin would work two times. I think it is wrong, isn't it? And it can break _(and, actually, it break my build process)_ somebody build process if it is doing something with output (e.g. wrapping it).
**What do you think about it? Is it needed or I'm too captious?**
And, I think we need to have some _FAQ for developers_ - even starting from 'how to roll out dev env for contributing brunch' - because that loadBrunch && loadGlobalBrunch, which appeared recently, made my day for a while when I tried to debug brunch :)
=> Fix duplicate dependencies in package.json

lib/modules.js
Hello there.
Using custom wrapper I found that there is code inconsistency. 
Please, look at:
line **34** in modules.js _(method **getModuleWrapper**)_
line **34** in source_file.js _(method **wrappedNode**)_
Everything will work fine if we will return a string, but custom wrapper defined by function returns object { data: string } which breaks source map for that file, because **identityNode** is not expecting the code will go from different file than passed _path_ parameter to it. 
So, we need:
* either to refactor identity node
* or allow custom wrappers to return prefix and suffix itself
* or just look at this PR
What do you think, guys?
=> Fix sourcemaps when using custom wrapper

lib/config.js, lib/plugins.js, package.json
This PR introduces config schema and types validation, as well as allows to centralize default values for various config keys via a simple descriptive DSL.
* errors and aborts brunch on incorrect types
* warns on deprecations
* warns on unrecognized `config.files` keys, for example, along with a list of possible values and suggestions
Sample error messages: 
* `config.paths.watched` won't be coerced into an array if string. probably ok nevertheless since the type mismatch error will tell it should be an array
`config.modules = false` won't be possible... but then, it is not even documented, which means it shouldn't be relied up
`config.paths.*` will now always be relative to root. The current behavior is that if custom paths aren't specified, then they are joined with root, but custom …
=> Config validation

docs/config.md, lib/config.js, lib/fs_utils/file_list.js, lib/fs_utils/pipeline.js, lib/fs_utils/source_file.js
See GH-1300
This allows to compile ES6 npm modules with babel.
The limitation is that for the time being only `.js` files are supported, as support of other extensions will probably require some more changes to deppack. Non-JS files are clearly not a priority so this should be ok. Eventually we will allow other extensions from npm packages. 
(GH-1309 ping @jahbini)
Related PRs:
- https://github.com/brunch/deppack/pull/24
- https://github.com/babel/babel-brunch/pull/30 
@paulmillr:
=> Allow .js files from node_modules/ to be compiled

lib/fs_utils/file_list.js, lib/fs_utils/write.js, lib/watch.js
https://github.com/brunch/brunch/issues/1320
I debugged that problem a bit more and also reviewed the history of related files.
Important milestones: 
1. https://github.com/brunch/brunch/commit/3b3d417266863debc7a612c3daf3955d3881ddcd
2. https://github.com/brunch/brunch/commit/62bc90106771d90768b02014317158cf64519678#diff-50761161d23ef09d8be139f4da670154
The changes:
1. `write.js`. I removed the `splice` call, since as I understand in the first commit listed above it was intended to prevent calling `generate` on removed files. After the second change I listed it isn't doing any useful work as I see. I also filtered removed files from `targets`, as it was in the initial version.
2. `watch.js`. I called `removeDisposedFiles`. I did that, because the file related to the removed dependency is …
=> An attempt to fix #1320

lib/config.js
If the package being required is in package.json but still can't be
loaded, that's a sign that an npm install is due, which this commit
introduces.
Note however that it does assume '.' as the root path, but given that
config's root can't be any place else, it should be ok.
=> Try to recover from MODULE_NOT_FOUND in the config

test/config.js, test/fixtures/config-with-overrides.js
Since 2.7.2, looks like brunch is not correctly merging some values when using the env option. I created a failing test case to illustrate this issue.
In the second test: `overrides the config using the specified env` the expected value for `config.paths.watched` is `['app', 'test']` but instead it returns `['app', 'test', 'vendor']`. In 2.7.1 this test pass.
=> Failing test with config override regression

lib/config.js
In general, paths should not be made absolute unless an absolute pass
was explicitly passed.
=> Fix a regression introduced by e80299

lib/config.js, lib/fs_utils/asset.js, lib/fs_utils/common.js, lib/fs_utils/file_list.js, lib/fs_utils/generate.js, lib/fs_utils/pipeline.js, lib/fs_utils/source_file.js, lib/fs_utils/write.js, lib/helpers.js, lib/hmr.js, lib/path.js, lib/plugins.js, lib/watch.js
Ref GH-1281
Allows to get rid of platform-specific path handling in config regexps,
et cetera, and also relieves plugins from having to care about that.
Filesystem access functions work just fine with the `/`s.
Paths consistency is acheieved by normalizing the paths that come from
the watcher and by providing a local drop-in replacement for the `path`
module which always returns paths with the `/`s.
---
Deppack PR: https://github.com/brunch/deppack/pull/30
@paulmillr to do:
=> Normalize paths to always use UNIX slashes internally

bin/brunch, lib/commands.js, lib/plugins.js, lib/run-cli.js, lib/watch.js
This allows to cleanly restart the watcher. The previous approach with
manually trying to clean require.cache didn't work well and produced
various memory leaks.
This commit changes the brunch init process: the binary does not
directly run brunch commands, but instead, creates a child process that
processed the commands. In case the child process needs to restart, it
kills it and runs another one.
It works properly under two conditions: both global brunch binary and
the local brunch installation contain this commit. If the global brunch
is older, or if the local brunch is older, the old behavior will be
preserved.
---
Note: what this means is there will be at least two processes when running `brunch watch` (but not other commands) — one that handles restarts, another that does the actual …
=> Make watcher restarts clean

.travis.yml, test/build.js
Too bad Travis doesn't do windows yet, having all builds also run Windows would have allowed us to catch Windows-only bugs early (now that we are normalizing paths to `/` this kind of an issue should be a rarity though)
Testing wise, the next steps could well be:
* setting expectations not only for `public` files content, but also for brunch output (errors, warnings, etc)
* then, roll out a headless webkit setup to allow to run the generated javascript and see if it executes without any errors (this will allow to catch a certain set of runtime issues, like the commonjs runtime)
=> Add tests for npm support

bin/brunch
When using brunch from the master branch, and linking with `npm link` I receive the following error in a project without a local brunch dependency:
```
module.js:341
throw err;
^
Error: Cannot find module '/home/marcio/workspace/javascript/brunch/cli.js'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at loadBrunch (/home/marcio/workspace/javascript/brunch/bin/brunch:52:3)
at loadGlobalBrunch (/home/marcio/workspace/javascript/brunch/bin/brunch:56:3)
at Object.<anonymous> (/home/marcio/workspace/javascript/brunch/bin/brunch:71:3)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
```
With this …
=> Fix brunch global bin path

bin/brunch, lib/watch.js
I added the BRUNCH_FORKED_PROCESS variable in the previous PR but your usage was incorrect, so the reload message will never trigger. Sorry for that.
=> Fix BRUNCH_FORKED_PROCESS global variable

docs/plugins.md, lib/fs_utils/asset.js, lib/fs_utils/file_list.js, lib/fs_utils/generate.js, lib/fs_utils/pipeline.js, lib/fs_utils/write.js, lib/plugins.js, lib/watch.js, package.json, test/_test_helper.js, test/build.js, test/watch.js
Changes to bring static asset compilation as to what @paulmillr and I have discussed.
This PR introduces an entirely new plugin API method: `compileStatic`. (`getDependencies` will then be used for both `compile` *and* `compileStatic` — as dependency discovery logic will be identical for both.)
The static asset compilation now will work on files from `app/assets`, this seems beneficial as it makes clear what will be compiled the regular way, and what will be compiled one-to-one. This means `app/index.jade` in will be a JS template, and `app/assets/index.jade` will turn into `public/index.html` — and both can be actually handled by the same plugin, `jade-brunch`, without having a separate plugin for this purpose.
=> Static compilation new take

package.json
It is very common at this point for brunch to be installed both globally and locally, or even locally-only within a project. This will eliminate the warning message npm currently spits out during local installation.
=> Remove `preferGlobal: true`

lib/fs_utils/asset.js
If you modify `conventions.assets` to include matches for certain file types for example: `/\.component\.css$/` it would cause an error because `Asset` couldn't determine the base folder to use to copy to the output folder. This `undefined` was causing an issue for `sysPath.relative`. Defaulting to an empty string allows for these files to be copied over from the root.
This allows for JS to live next to HTML or CSS in the same folder and have the latter plucked out as assets while the code is compiled. Combined with the new static compilation functionality, this is quite powerful.
A further step in the future might allow for this default root to be customized (to say `app`) allowing references to these URLs to drop some leading folder segments.
=> Default non-matching asset directory to root

lib/index.js
Closes GH-1413
It was caused by the use of backticks inside a logger message. When
spawning a growl notification, these caused the shell to start both of
the wrapped commands, resulting in a loop.
Couldn't find a way to properly escape these, so not using them
altogether for now.
=> Prevent spawning a lot of processes when misusing brunch new

lib/plugins.js, lib/watch.js
This change exposes plugins.preCompilers as a function that generates a new set
of preCompile promises on every compile phase.
This resolves #1406 and returns preCompile hooks to their original behaviour.
=> Allow preCompile to run before every compile phase.

bin/brunch
Some process managers like [concurrently](https://github.com/kimmobrunfeldt/concurrently) sends a SIGTERM signal for the current process. But since the watcher server is actually called in a child process, this process wasn't being properly finished generating a phantom process. This PR fixes that.
=> Kill child process on sigterm signal

bin/brunch, lib/commands.js, lib/config.js, lib/fs_utils/asset.js, lib/fs_utils/file_list.js, lib/fs_utils/generate.js, lib/fs_utils/pipeline.js, lib/fs_utils/source_file.js, lib/fs_utils/write.js, lib/helpers.js, lib/hmr.js, lib/index.js, lib/modules.js, lib/path.js, lib/plugins.js, lib/polyfills.js, lib/run-cli.js, lib/watch.js, lib/workers/job-processor.js, lib/workers/manager.js, package.json
1. removed `deep-assign` dependency, extracted reusable `customDeepAssign` to helpers; added `filter` as third attribute
2. added lightweight `Array#includes`, `Object.values` and `Object.entries` shims
3. moved `deepFreeze` to helpers; added optional second param
4. refactored `plugins.js`: more cohesion, pure functions, less additional params and index checking
5. replaced `Promise.resolve` with `return` and `Promise.reject` with `throw` in `Promise#then`
6. added more template strings in more places
7. various code style and type coercion fixes
=> refactor & remove deep-assign

.travis.yml
Since according to this comment, brunch supports Node.js 4:
https://github.com/babel/babel-brunch/pull/33#issuecomment-229130296
=> Run Travis on Node.js 4 as well

lib/config.js, lib/fs_utils/pipeline.js, lib/helpers.js, lib/polyfills.js, lib/watch.js, test/build.js
1. Removed deprecated `fs.exists`, moved fs helpers to `helpers.js`.
2. Refactored `loadComponents`.
3. `addPackageManagers` does not wait for `component.json` deprecation warning.
4. Removed `setProp` helper and refactored `checkProjectDependencies`.
5. Handled couple edge cases in polyfills.
=> Allow disabling bower

lib/config-validate.js, lib/fs_utils/generate.js, test/build.js
=> Add "inline" option for inline source maps.

lib/config.js, test/config.js, test/fixtures/config-with-trailing-slashes.js
Our internal code expects that the `config.paths.public` and
`config.paths.watched` paths don't end with a trailing slash.
For example, in `lib/fs_utils/generate.js` line 213, we have this:
```js
const len = config.paths['public'].length + 1;
const joinKey = path.slice(len);
```
If we had a trailing slash in the end of the public path, the joinKey
might be different then what we expect.
Another example, in `lib/config.js` line 185, we have:
```js
const isTargetWatched = paths.watched.some(path => target.startsWith(`${path}/`));
```
It appends a trailing slash to the path.
***Note***
I don't think this is the best solution, but given that I'm not 100%
familiar with brunch's source code, and there may be more instances of
code that doesn't expect a trailing slash, sanitizing user input …
=> Normalize/sanitize config.paths with trailing slashes

lib/index.js
Someone forgot to remove backslash.  https://github.com/brunch/brunch/commit/e23eb42812e2bcb299883e745cf7ac60c3fddd12
=> Remove backslash from the error string.

bin/brunch
This PR adds ability to debug Brunch using `node --inspect --debug-brk`. Let's forget about `console.log`ing!
Now, if `NODE_ENV` environment variable is set to `development`, ` --inspect` and `--debug-brk` flags will be passed as arguments to forked process.
**For example:**
```sh
$ NODE_ENV='development' brunch watch
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/f773c7f2-7f84-4c51-8c02-fd3e230e2205
```
**In Google Chrome:**
=> Add ability to debug using node --inspect.

lib/index.js
I've found the real cause of this issue. We require `watch` before we assign `process.env.DEBUG` any value, so it's `undefined` and debug messenges are not shown.
Commit that introduce the issue: https://github.com/brunch/brunch/commit/34bab856ba82ce8d3700b54bf695f2e87098171b
---
#1595 is a bad solution, so it have to be closed.
=> Fix debug. Close #1592

lib/utils/helpers.js
Before:
$ brunch b
29 Dec 14:22:58 - error: Compiling of app/test.js failed. SyntaxError: app/test.js: super() is only allowed in a derived constructor
2 |   constructor() {
3 |     this.foo = 1
> 4 |     super()
|     ^
5 |   }
6 | }
7 |
29 Dec 14:22:58 - error: Compiling of app/test.scss failed. Error: Invalid CSS after "  background-color": expected "}", was ": white"
on line 3 of app/test.scss
>>   background-color: white
--^
29 Dec 14:22:58 - info: compiled in 815 ms
After:
$ brunch b
29 Dec 14:21:48 - error: Compiling of app/test.scss failed.
Error: Invalid CSS after "  background-color": expected "}", was ": white"
on line 3 of app/test.scss
>>   background-color: white
--^
29 Dec 14:21:48 - error: Compiling of app/test.js failed.
SyntaxError: app/test.js: super() is only allowed …
=> Improve error messages

CHANGELOG.md
I've added this option only for debugging of Brunch.
=> Remove `node --inspect` from CHANGELOG.md

lib/utils/config.js
The changes in #1608 introduced a bug where brunch will overwrite any user-set value for the `NODE_ENV` environment variable.
For example, the following shell script...
```
export NODE_ENV=staging
node_modules/.bin/brunch build
```
...will build the project with `development` settings, even when I have explicitly set the `NODE_ENV`.
This effectively breaks using more than two environments. I use brunch in conjunction with [the `config` NPM module](https://www.npmjs.com/package/config), and with the current brunch code I cannot build with `staging` settings.
The fix is two-fold:
* Avoid setting a value for `NODE_ENV` if `NODE_ENV` already has a value
* Force the `--production` option if `NODE_ENV` is already set to `production` (e.g. `export NODE_ENV=production; brunch build`)
=> Do not overwrite the NODE_ENV environment variable

lib/utils/config-validate.js
Fix for #1628 and #1593. Solution related to https://github.com/brunch/brunch/issues/1593#issuecomment-269223215
Caused by https://github.com/brunch/brunch/pull/1571/commits/247e91ae50fa8d90680caa6a3c45632d3eeaab2c.
@shvaikalesh did [a small unobvious mistake](https://github.com/brunch/brunch/pull/1571/commits/247e91ae50fa8d90680caa6a3c45632d3eeaab2c#diff-9414a6c7096b68cca1b48e1215cf64a8R77) in regular expression. When Brunch is installed globally,  we get a relative path to global Brunch's `process/browser.js`, such as:
```
../path/to/global/brunch/node_modules/process/browser.js
```
… which is usually do not match to `/^(bower_components|node_modules|vendor)\//`, because it doesn't start with `node_modules`.
You can find more precise explanation here: …
=> Fix vendor pattern.

lib/fs_utils/generate.js
brunch sets the private `._sourcesContents` property of source maps that
come from optimizers:
map._sourcesContents[`$${path}`] = source
The reason every `path` is prefixed with a `$`, is because the
`mozilla/source-map` module used to do so, but that changed in
mozilla/source-map#228. Now, only the string `__proto__` is prefixed
with a `$`, but not if the runtime supports "null __proto__". If
`!('__proto__' in Object.create(null))` is `true`, the
`mozilla/source-map` module will never prefix any paths with a `$`.
Does Node.js support "null __proto__"?
$ node -p "!('__proto__' in Object.create(null))"
true
So, yes it does. I've tested with Node.js 4, 6 and 7.
This commit simply gets rid of the `$` prefixing.
Before:
$ brunch build --production
19 Jan 20:28:08 - info: compiled main.js into …
=> Fix "sourcesContent" after optimizers are run

lib/fs_utils/pipeline.js, lib/utils/helpers.js, lib/utils/plugin-adapter.js
Refactorings aside, this PR:
1) requires plugins with `compileStatic` have `type` equal to `template`
2) makes plugin API a bit more forgiving (e.g. no need to wrap result in `Promise.resolve`)
3) fixes `formatError` swallowing stack traces
4) fixes "takes too long to compile" appearing after compilation failed
=> Changes to plugin adapter

package.json
Hi,
I have tested coffee-script latest version and it seems to work perfectly. Is it possible to update bump it to the latest version through this PR ? And also publish the changes to NPM ?
Thanks
=> Bump coffee-script to version 1.12.7

lib/fs_utils/generate.js
This seems to work for me, but I'm not sure of the ramifications.
Anyone having problems with sourcemaps in Brunch 2.10, please check this out.
=> Possible sourcemaps fix

lib/fs_utils/generate.js, lib/fs_utils/source_file.js
Fixes #1635: Generating source maps with the correct source code and line numbers.
Tested and working in both production and dev mode with buble, uglify.js, postcss and clean-css.
More tests would be appreciated (if you're usiging yarn, you can add the fix from my branch with `yarn add https://github.com/friday/brunch\#fix/wrong-sm-property`, but this branch won't live long so don't keep it after testing).
The problem:
`_updateCache()` in "source_file.js" passed `file.sourceMap` to `_updateMap()`. However `file.sourceMap` doesn't seem to exist. I think it did in 2.9, but was renamed to file.map (or at least file.map exists and using it instead of `file.sourceMap` fixed the problem completely for me).
This also reverts #1756 since it's only fixing the "symptom" (`isIdentity` always being …
=> Fix source maps

lib/fs_utils/source_file.js
Allows non-CSS compilers (`template` and `javascript`) to emit CSS code that will be processed by Brunch.
This is useful for single-file Vue.js plugins, as they emit both JS and CSS. Currently, `vue-brunch` relies on injecting CSS using Javascript or dumping the unprocessed CSS to a separate file.
This change is similar to #1240.
How to use it:
```
class MyCompiler {
compile(params) {
const compiled = magic(params);
const cssExports = ".red { color: #f00 }";
return Promise.resolve({ data: compiled, cssExports });
}
}
```
=> Allow non-CSS compilers to optionally emit CSS modules

lib/fs_utils/pipeline.js
Fixes #1722.
EDIT: the failed test is `chokidar` & Node.js v9 issue, not relevant.
=> Merge dependencies

README.md
This note dates back 5y ago, long before [`native-notifier`](https://github.com/paulmillr/native-notifier) was introduced to handle notifications w/o native dependencies.
=> Remove note about `terminal-notifier`

lib/utils/config.js
=> Don’t override NODE_ENV in production mode (fixes #1692)
