- src/watch.coffee
Works with `config.preCompile`, `Plugin.prototype.compile`. 
Syntax:
`config.coffee`
```coffeescript
config = 
preCompile: (end) ->
console.log('Prepare for compiling')
end()
```
`plugin.coffee`
```coffeescript
#...
MyPlugin.prototype.preCompile (end) ->
#do something...
end()
```
Also, available [before-brunch plugin](https://github.com/yavorsky/before-brunch).
> Implement preCompile

- src/cli.coffee
- src/watch.coffee
> Optionally set project path from CLI command

- docs/README.md
As per https://github.com/brunch/brunch-guide/issues/4
> Added link to guide at top of docs

- docs/config.md
Add instructions to add ignore conventions, including the default ignore
pattern.
> config.md - default ignore pattern

- .editorconfig
- .gitignore
- lib/fs_utils/asset.js
- lib/fs_utils/common.js
- lib/fs_utils/file_list.js
- lib/fs_utils/generate.js
- lib/fs_utils/pipeline.js
- lib/fs_utils/source_file.js
- lib/fs_utils/write.js
- lib/helpers.js
- lib/promise.js
- lib/watch.js
- lib/worker.js
- package.json
> Use promises instead of callbacks

- README.md
- docs/commands.md
Looks like these doc changes slipped through the cracks. :memo:
> Switch the -p and -P flag documentation

- lib/helpers.js
This fixes the unit tests. This should make Travis happy for my two other PRs
> Missing a break

- lib/fs_utils/pipeline.js
> Force the linter as function context

- lib/ui.js
- lib/watch.js
- package.json
This will make Brunch print the "compiling" message after 5 seconds of the build have elapsed, and the three dots are animated to further indicate that it is still compiling.
#1057
> Improve UI for long builds

- lib/application.js
> Bubble up require errors from within the config

- LICENSE
> It's 2016 now

- docs/config.md
Clarified something that tripped me up and noticed some of the docs were wrong.
> Update npm descriptions

- lib/ui.js
> Fix build hangup

- lib/deppack.js
> Throw more descriptive errors from deppack

- docs/faq.md
Fixes for FAQ for 2.2 according to https://github.com/brunch/brunch/pull/1120
> NPM integration FAQ fix

- lib/deppack.js
> Fix relative parent require detection

- lib/deppack.js
> Fix for browser package overrides

- lib/server.js
Had some issues with remote access to the server. The server was listen on localhost. Now it is possible to change the hostname in the brunch-config file with `config.server.hostname`.
> Added support for custom hostnames.

- lib/deppack/explore.js
- lib/deppack/init.js
- lib/deppack/resolve.js
- lib/mediator.js
So that the backbone:exoskeleton alias means backbone isn't included in
the final bundle.
> Respect aliases during dependency discovery

- docs/config.md
- lib/deppack.js
- lib/deppack/explore.js
- lib/deppack/helpers.js
- lib/deppack/init.js
> Allow to statically include files from npm packages

- lib/deppack/modules.js
> Export getModuleRootName from deppack/modules for error messages

- docs/config.md
- docs/plugins.md
- lib/plugins.js
- lib/watch.js
> Pass changed assets to onCompile

- lib/application.js
- lib/deppack/explore.js
- lib/mediator.js
https://github.com/brunch/brunch/issues/1161#issuecomment-183551321
cc @razor-x
> Substitute process.env.NODE_ENV with production/development

- lib/server.js
> Fix handling of custom servers

- lib/fs_utils/generate.js
> Handle cases when config.files[javascript] is not always present.

- lib/deppack/modules.js
- lib/deppack/resolve.js
> Include file-based aliases for main files

- lib/deppack/modules.js
> Add a temporary option to disable file-based module name generation

- lib/application.js
- lib/fs_utils/generate.js
- lib/watch.js
related: https://github.com/brunch/commonjs-require-definition/pull/13
> No components

- lib/deppack/modules.js
> Fix qualified .json require handling

- lib/deppack/explore.js
- lib/deppack/modules.js
Also fix a few bugs discovered while making scoped modules work in #1213 sample repo.
> Introduce support for NPM @scoped/packages

- lib/deppack/modules.js
- lib/deppack/resolve.js
Based on report here http://stackoverflow.com/questions/35711331/brunch-issue-trying-to-bundle-socket-io-client
---
@paulmillr do you think we can move the extensions PRs forward?
> Make relative requires from browser'd files work

- lib/deppack/deppack.js
> Properly expose npm packages via globals

- lib/config.js
- test/helpers.js
> Take into account public folder override when configuring server

- lib/watch.js
- lib/workers/manager.js
> Don't set jobs count unless the option was passed

- lib/config.js
- lib/watch.js
> Make auto-npm-install aware of production env flag

- lib/fs_utils/write.js
> Fix a type error when checkin if a file was written

- lib/fs_utils/source_file.js
> Make pipeline receive normalized path

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- README.md
@VitaliyR in #1306 reminded us that we should ease the entry for these who wish to try and fix the bugs they are experiencing themselves, or add a new feature.
I've written a simple contributing document that gives bird's eye overview of the various components of Brunch, as well as includes the steps to use the cloned fork locally (since not everyone might have even heard of `npm` commands other that `install`)
What do you think? @paulmillr @es128 
@VitaliyR, do you think this would have helped you even a bit? Is there anything else you think we should make sure to include there?
I thinking about outlining the brunch build process (aka which function in which file is called to compile a file, which is called after it, etc)...
> Write the contributing document

- lib/config.js
> Fix a config.paths.watched regression

- lib/config.js
> Throw an error when using deppack with non-CommonJS modules

- lib/config.js
- lib/watch.js
- package.json
@lydell in https://github.com/brunch/brunch/issues/1294#issuecomment-214164581 suggested a few ideas on improving our error messages, to make them friendlier and more actionable.
- Warn when there is nothing to compile
- Friendlier and more suggestive config and package.json errors
@paulmillr:
> Some improvements to error messages

- lib/config.js
> Provide production overrides default

- lib/config.js
> Fix entry points warning on Windows

- lib/config.js
This allows to specify an absolute path as one of the watched.
https://github.com/brunch/brunch/issues/894#issuecomment-215677786
> Resolve watched paths instead of just joining

- lib/config.js
- test/config.js
- test/fs_utils.common.js
- test/fs_utils.generate.js
- test/helpers.js
PR for issue #1336 
Running `npm test` I got `✖ 2 problems (1 error, 1 warning)` but looking at [build](https://travis-ci.org/brunch/brunch/jobs/127817268) I think this problem was present before, so I think, I didn't break  anything.
> replace same by deepEqual

- lib/config.js
- package.json
- test/.eslintrc.json
- test/config.js
Here some test improvements also some eslint fixes for `async`.
> improve specs, fix eslint for ava async

- docs/faq.md
> Fix a files.styles typo in FAQ

- docs/config.md
- lib/config.js
https://github.com/brunch/brunch/issues/1345
> Don't enable babel-brunch for npm modules by default

- lib/fs_utils/asset.js
- lib/watch.js
https://github.com/brunch/deppack/pull/31
> Supporting changes for improved deppack new/deleted file handling

- .gitignore
- lib/fs_utils/asset.js
- package.json
- test/.eslintrc.json
- test/_test_helper.js
- test/build.js
While creating some additional tests for brunch I noticed a typo in the destinationPath property.
So I'm opening a PR here to validate if the way I'm testing looks good and also bring the destinationPath fix.
> Create some build tests and fix an issue with destinationPath

- lib/watch.js
Requires: https://github.com/brunch/deppack/pull/32
> Supporting changes for compiling node_modules

- .travis.yml
- bin/brunch
- lib/fs_utils/file_list.js
- lib/watch.js
- package.json
- test/_test_helper.js
- test/build.js
- test/watch.js
This PR create some additional tests for `brunch build` and `brunch watch`.
> Additional tests

- lib/config.js
For https://github.com/brunch/brunch/issues/1378
> Add 'detectProcess' flag to npm config.

- lib/fs_utils/pipeline.js
> Normalize file deps

- lib/config.js
to accept boolean or an array of string as described in official documentation
> fix <notifications> validation

- lib/fs_utils/generate.js
- lib/fs_utils/pipeline.js
- lib/helpers.js
> Print warnings when plugins take too long to process

- lib/fs_utils/file_list.js
> Use String#startsWith

- lib/fs_utils/asset.js
- lib/fs_utils/generate.js
- lib/fs_utils/pipeline.js
- lib/helpers.js
- lib/watch.js
- package.json
https://github.com/brunch/brunch/pull/1427
> Apply notes from prev PR review

- lib/cli.js
- lib/commands.js
- lib/config-validate.js
- lib/config.js
- lib/error.js
- lib/fs_utils/asset.js
- lib/fs_utils/file_list.js
- lib/fs_utils/generate.js
- lib/fs_utils/pipeline.js
- lib/fs_utils/source_file.js
- lib/fs_utils/write.js
- lib/helpers.js
- lib/hmr.js
- lib/messages.json
- lib/modules.js
- lib/plugins.js
- lib/watch.js
- test/helpers.js
1. Separated Brunch config validation to separate file for better cohesion.
2. Removed `mediator` from `config.js`, it looked like quick & dirty solution. Now `isProduction` is passed via `params` and normalized with `ToBoolean`.
3. Introduced `BrunchError` class.
4. Improved error type detection.
> improve error handling & refactor

- lib/fs_utils/write.js
- lib/plugins.js
- lib/watch.js
Our lint tests weren't passing.
This lines of code had the wrong indentation.
> Fix eslint errors (tests)

- .gitignore
- lib/config-validate.js
- lib/fs_utils/write.js
Closes https://github.com/brunch/brunch/issues/1443
> add hot to config schema

- lib/utils/config.js
- lib/watch.js
> Revert "Fix preCompile infinite build"

- lib/utils/messages.json
This relates not only to plugins :)
> Patch related to ##1486. `--save` -> `--save-dev`

- lib/cli.js
As requested in #1509, let's allow user to specify a path to their brunch-config file.
> Allow usage of --config param

- lib/index.js
Suggested in https://github.com/brunch/brunch/pull/1596#issuecomment-268904719
> Add comment for #1596

- lib/utils/helpers.js
$ sign was replaced with another one $ sign
https://github.com/brunch/brunch/issues/1603
> Fix for issue #1603. Fixed bug with $ sign in notifications.

- lib/utils/helpers.js
> Revert "Fix for issue #1603. Fixed bug with $ sign in notifications."

- lib/fs_utils/file_list.js
- lib/fs_utils/source_file.js
- lib/fs_utils/write.js
- lib/utils/config.js
- lib/utils/plugins.js
Closes https://github.com/brunch/brunch/issues/1621
Caused by https://github.com/brunch/brunch/pull/1571
Thanks @lydell
> Fix isHelper & clean up config.js

- lib/utils/plugins.js
Closes #1647
Huge thanks @denar90
> Fix isHelper

- lib/utils/config.js
- package.json
> chore(package.json): coffee-script is renamed

- .travis.yml
Remove dated node.js v7, add v8 LTS & v9
> Update node.js environment on Travis CI

- lib/utils/config.js
Changed entrypoints warning to an error and made the error clearer
for the developer. Made it clearer how to fix the issue if
it is a problem
> ref(entrypoints): Changed entrypoint error message

- lib/fs_utils/generate.js
- lib/utils/config-validate.js
- lib/utils/plugins.js
- test/build.js
Reverts "remove plugins.order" (c759c745 from #1522)
Resolves #1377
> Readd plugins.order (fixes #1377)

- .gitignore
- lib/init-skeleton.js
- package.json
> Use https() instead of git()
